return {
  version = 1,
  format = "native",
  width = 9,
  height = 10,
  centerQ = 4,
  centerR = 4,
  orientation = "flat",
  activeRows = {
    [0] = {3, 5},
    [1] = {1, 7},
    [2] = {0, 8},
    [3] = {0, 8},
    [4] = {0, 8},
    [5] = {0, 8},
    [6] = {0, 8},
    [7] = {0, 8},
    [8] = {2, 6},
    [9] = {4, 4},
  },
  terrain = {
    ["0,3"] = "water",
    ["0,4"] = "water",
    ["0,5"] = "water",
    ["1,4"] = "water",
    ["1,5"] = "water",
    ["8,3"] = "water",
    ["8,4"] = "water",
    ["8,5"] = "water",
    ["7,4"] = "water",
    ["7,5"] = "water",
  },
  entities = {
    ["4,0"] = { name = "MountainRange", cells = { {1,1},{2,1},{3,0},{4,0},{5,0},{6,1},{7,1} } },
    ["0,4"] = { name = "SlopeRange", cells = { {0,2},{0,3},{0,4},{0,5},{0,6},{0,7} } },
    ["8,4"] = { name = "SlopeRange", cells = { {8,2},{8,3},{8,4},{8,5},{8,6},{8,7} } },
    ["3,8"] = { name = "ReefRange", cells = { {1,7},{2,8},{3,8},{4,9},{5,8},{6,8},{7,7} } },
    -- Enemies: some standing on the belt, some off it
    ["3,4"] = "Zombie",
    ["5,4"] = "Zombie",
    ["2,3"] = "Zombie",
    ["6,3"] = "Lich",
    ["4,6"] = "Zombie",
    ["2,6"] = "SmallBuilding",
    ["6,6"] = "SmallBuilding",
  },
  statuses = {},
  upper_terrain = {
    -- Conveyor belt along row 4, pushing eastward along the row (screen: south-east)
    ["2,4"] = "conveyor:se",
    ["3,4"] = "conveyor:se",
    ["4,4"] = "conveyor:se",
    ["5,4"] = "conveyor:se",
    ["6,4"] = "conveyor:se",
    -- Return belt along row 2, pushing westward along the row (screen: north-west)
    ["2,2"] = "conveyor:nw",
    ["3,2"] = "conveyor:nw",
    ["4,2"] = "conveyor:nw",
    ["5,2"] = "conveyor:nw",
    ["6,2"] = "conveyor:nw",
  },
  elevation = {
    ["1,2"] = true,
    ["7,2"] = true,
  },
}
