return {
  version = 1,
  format = "native",
  width = 9,
  height = 10,
  centerQ = 4,
  centerR = 4,
  orientation = "flat",
  border = "mountain",
  activeRows = {
    [0] = {3, 5},
    [1] = {1, 7},
    [2] = {0, 8},
    [3] = {0, 8},
    [4] = {0, 8},
    [5] = {0, 8},
    [6] = {0, 8},
    [7] = {0, 8},
    [8] = {2, 6},
    [9] = {4, 4},
  },
  terrain = {
    ["0,3"] = "water",
    ["0,4"] = "water",
    ["0,5"] = "water",
    ["1,4"] = "water",
    ["1,5"] = "water",
    ["8,3"] = "water",
    ["8,4"] = "water",
    ["8,5"] = "water",
    ["7,4"] = "water",
    ["7,5"] = "water",
  },
  entities = {
    -- Enemies around the retractable highground
    ["2,2"] = "Zombie",
    ["6,2"] = "Zombie",
    ["3,5"] = "Zombie",
    ["5,5"] = "Zombie",
    ["4,6"] = "Lich",
    ["2,6"] = "SmallBuilding",
    ["6,6"] = "SmallBuilding",
  },
  statuses = {},
  upper_terrain = {},
  elevation = {
    -- Static highground corners
    ["1,2"] = true,
    ["2,2"] = true,
    ["7,2"] = true,
    ["6,2"] = true,
  },
  -- Retractable highground: toggled by the Highground button (1-turn cooldown)
  retractable = {
    ["3,3"] = true,
    ["4,3"] = true,
    ["5,3"] = true,
  },
}
