return {
  version = 1,
  format = "native",
  width = 9,
  height = 10,
  activeRadius = 4,
  centerQ = 4,
  centerR = 4,
  orientation = "flat",
  activeRows = {
    [0] = {3, 5},
    [1] = {1, 7},
    [2] = {0, 8},
    [3] = {0, 8},
    [4] = {0, 8},
    [5] = {0, 8},
    [6] = {0, 8},
    [7] = {0, 8},
    [8] = {2, 6},
    [9] = {4, 4},
  },
  terrain = {
    ["5,6"] = "sand",
    ["5,7"] = "water",
    ["5,8"] = "sand",
    ["6,1"] = "water",
    ["6,2"] = "water",
    ["6,3"] = "sand",
    ["6,4"] = "sand",
    ["6,5"] = "sand",
    ["6,6"] = "sand",
    ["6,7"] = "water",
    ["6,8"] = "grass",
    ["7,1"] = "water",
    ["7,2"] = "sand",
    ["7,3"] = "sand",
    ["7,4"] = "sand",
    ["7,5"] = "sand",
    ["7,6"] = "water",
    ["8,2"] = "sand",
    ["8,3"] = "sand",
    ["8,4"] = "sand",
    ["8,5"] = "sand",
    ["8,6"] = "sand",
    ["0,2"] = "sand",
    ["0,3"] = "sand",
    ["0,4"] = "sand",
    ["0,5"] = "sand",
    ["0,6"] = "sand",
    ["0,7"] = "sand",
    ["1,1"] = "sand",
    ["1,2"] = "grass",
    ["1,3"] = "grass",
    ["1,4"] = "grass",
    ["1,5"] = "water",
    ["1,6"] = "water",
    ["1,7"] = "grass",
    ["2,1"] = "sand",
    ["2,2"] = "grass",
    ["2,3"] = "grass",
    ["2,4"] = "grass",
    ["2,5"] = "sand",
    ["2,6"] = "water",
    ["2,7"] = "water",
    ["2,8"] = "grass",
    ["3,0"] = "sand",
    ["3,1"] = "grass",
    ["3,2"] = "grass",
    ["3,3"] = "grass",
    ["3,4"] = "sand",
    ["3,5"] = "sand",
    ["3,6"] = "water",
    ["3,7"] = "water",
    ["3,8"] = "sand",
    ["4,0"] = "sand",
    ["4,1"] = "sand",
    ["4,2"] = "grass",
    ["4,3"] = "grass",
    ["4,4"] = "sand",
    ["4,5"] = "sand",
    ["4,6"] = "sand",
    ["4,7"] = "water",
    ["4,8"] = "sand",
    ["4,9"] = "sand",
    ["5,0"] = "sand",
    ["5,1"] = "water",
    ["5,2"] = "grass",
    ["5,3"] = "sand",
    ["5,4"] = "sand",
    ["5,5"] = "sand",
  },
  entities = {
    ["4,0"] = { name = "MountainRange", cells = { {1, 1}, {2, 1}, {3, 0}, {4, 0}, {5, 0}, {6, 1}, {7, 1}} },
    ["2,3"] = "Caravan",
    ["2,5"] = "Caravan",
    ["0,4"] = { name = "SlopeRange", cells = { {0, 2}, {0, 3}, {0, 4}, {0, 5}, {0, 6}, {0, 7}} },
    ["4,6"] = "Caravan",
    ["6,3"] = "Caravan",
    ["8,4"] = { name = "SlopeRange", cells = { {8, 2}, {8, 3}, {8, 4}, {8, 5}, {8, 6}, {8, 7}} },
    ["3,2"] = "BigBuilding",
    ["4,4"] = "Caravan",
    ["3,8"] = { name = "ReefRange", cells = { {1, 7}, {2, 8}, {3, 8}, {4, 9}, {5, 8}, {6, 8}, {7, 7}} },
  },
  statuses = {
    ["5,6"] = {"fire"},
    ["6,6"] = {"fire"},
  },
  upper_terrain = {
  },
  elevation = {
    ["2,2"] = true,
    ["4,1"] = true,
    ["0,2"] = true,
    ["0,3"] = true,
    ["3,0"] = true,
    ["3,1"] = true,
    ["1,2"] = true,
    ["5,0"] = true,
    ["1,1"] = true,
    ["4,0"] = true,
    ["2,1"] = true,
  },
}