return {
  version = 1,
  format = "native",
  width = 9,
  height = 10,
  centerQ = 4,
  centerR = 4,
  orientation = "flat",
  activeRows = {
    [0] = {3, 5},
    [1] = {1, 7},
    [2] = {0, 8},
    [3] = {0, 8},
    [4] = {0, 8},
    [5] = {0, 8},
    [6] = {0, 8},
    [7] = {0, 8},
    [8] = {2, 6},
    [9] = {4, 4},
  },
  terrain = {
    ["8,2"] = "sand",
    ["8,3"] = "sand",
    ["8,4"] = "sand",
    ["8,5"] = "sand",
    ["8,6"] = "sand",
    ["0,2"] = "sand",
    ["0,3"] = "sand",
    ["0,4"] = "sand",
    ["0,5"] = "sand",
    ["0,6"] = "sand",
    ["0,7"] = "sand",
    ["1,1"] = "sand",
    ["1,2"] = "grass",
    ["1,3"] = "railway",
    ["1,4"] = "grass",
    ["1,5"] = "sand",
    ["1,6"] = "sand",
    ["1,7"] = "grass",
    ["2,1"] = "sand",
    ["2,2"] = "grass",
    ["2,3"] = "railway",
    ["2,4"] = "grass",
    ["2,5"] = "sand",
    ["2,6"] = "sand",
    ["2,7"] = "railway",
    ["2,8"] = "sand",
    ["3,0"] = "sand",
    ["3,1"] = "grass",
    ["3,2"] = "railway",
    ["3,3"] = "grass",
    ["3,4"] = "sand",
    ["3,5"] = "sand",
    ["3,6"] = "railway",
    ["3,7"] = "sand",
    ["3,8"] = "sand",
    ["4,0"] = "sand",
    ["4,1"] = "sand",
    ["4,2"] = "railway",
    ["4,3"] = "grass",
    ["4,4"] = "water",
    ["4,5"] = "sand",
    ["4,6"] = "railway",
    ["4,7"] = "sand",
    ["4,8"] = "sand",
    ["4,9"] = "sand",
    ["5,0"] = "sand",
    ["5,1"] = "railway",
    ["5,2"] = "grass",
    ["5,3"] = "sand",
    ["5,4"] = "sand",
    ["5,5"] = "railway",
    ["5,6"] = "sand",
    ["5,7"] = "sand",
    ["5,8"] = "sand",
    ["6,1"] = "sand",
    ["6,2"] = "sand",
    ["6,3"] = "sand",
    ["6,4"] = "sand",
    ["6,5"] = "railway",
    ["6,6"] = "sand",
    ["6,7"] = "sand",
    ["6,8"] = "sand",
    ["7,1"] = "sand",
    ["7,2"] = "sand",
    ["7,3"] = "sand",
    ["7,4"] = "railway",
    ["7,5"] = "sand",
    ["7,6"] = "sand",
  },
  entities = {
    ["5,3"] = "WeakMountain",
    ["5,7"] = "SuperMountain",
    ["3,7"] = "SuperMountain",
    ["1,6"] = "SuperMountain",
    ["6,7"] = "SuperMountain",
    ["3,4"] = "WeakMountain",
    ["7,6"] = "SuperMountain",
    ["1,3"] = "TunnelExit",
    ["7,3"] = "TunnelEntrance",
    ["5,1"] = "TunnelEntrance",
    ["2,7"] = "TunnelExit",
    ["4,0"] = { name = "MountainRange", cells = { {1,1},{2,1},{3,0},{4,0},{5,0},{6,1},{7,1} } },
    ["0,4"] = { name = "SlopeRange", cells = { {0,2},{0,3},{0,4},{0,5},{0,6},{0,7} } },
    ["8,4"] = { name = "SlopeRange", cells = { {8,2},{8,3},{8,4},{8,5},{8,6},{8,7} } },
    ["3,8"] = { name = "ReefRange", cells = { {1,7},{2,8},{3,8},{4,9},{5,8},{6,8},{7,7} } },
  },
  statuses = {
    ["4,1"] = {"fire"},
  },
  upper_terrain = {
  },
}
